FROM nginx:alpine

# Create directories
WORKDIR /usr/share/nginx/html

# Copy static files
COPY public/ .

# Copy nginx configuration
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf

# Expose port
EXPOSE 80

# Start nginx
CMD ["nginx", "-g", "daemon off;"]
