FROM nginx:alpine

# Copy nginx configuration for production
COPY nginx.prod.conf /etc/nginx/nginx.conf
COPY conf.d /etc/nginx/conf.d

# Create ssl directory
RUN mkdir -p /etc/nginx/ssl

# Expose ports
EXPOSE 80
EXPOSE 443

# Start Nginx server
CMD ["nginx", "-g", "daemon off;"]
